spring:
  profiles:
    active: dev # 指定profile
  application:
    name: lims-sys-manage
server:
  servlet:
    context-path: /sys
aj:
  captcha:
    # 缓存类型
    cache-type: redis
    # blockPuzzle 滑块 clickWord 文字点选  default默认两者都实例化
    type: clickword
    # 右下角显示字
    water-mark: lims
    # 校验滑动拼图允许误差偏移量(默认5像素)
    slip-offset: 5
    # aes加密坐标开启或者禁用(true|false)
    aes-status: true
    # 滑动干扰项(0/1/2)
    interference-options: 2
