# 服务配置
server:
  port: 8081
#spring配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lims?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
    username: root
    password: root

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  # flyway
  flyway:
    locations: classpath:db/migration # 迁移脚本的位置
    baseline-on-migrate: true # 在没有元数据表的情况下，针对非空Schema执行迁移时是否自动调用基线
    enabled: true
    sql-migration-prefix: V
    sql-migration-suffixes: .sql

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印
  mapper-locations: classpath*:/mapper/**Mapper.xml


springfox:
  documentation:
    swagger:
      v2:
        enabled: true

