version: "3.8"
services:
  lims-sample-8091:
    image: zhengpanone/jdk8:latest
    container_name: lims-sample-8091
    working_dir: /project
    ports:
      - "8091:8091"
    volumes:
      - ./lims-sample-manage.jar:/project/lims-sample-manage.jar
    command: java -Xms512M -Xmx512M  -jar -Duser.timezone=GMT+08 /project/lims-sample-manage.jar
